---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# ===================================================================================
# --- LA MIA DISTRO
# ===================================================================================
# Nata in risposta a Nobara, non a caso ho scelto una mia waifu per il nome
# Potrebbe passare a Balalaika, Roberta, Medusa... o anche Aizen... o persino essre il primo passo per il mio sogno, Vesta
name: chiyuki
# description will be included in the image's metadata
description: ISO a uso personale, per test e lavoro.
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
modules:

# ===================================================================================
# --- OS RELEASE
# ===================================================================================
  - type: os-release
    properties:
      ID: chiyuki
#      VERSION_ID: 44
      VERSION_CODENAME: Aaroniero # personaggi di Bleach per la 0.x
      NAME: chiyuki
      PRETTY_NAME: Chiyuki (AuroraOS)
#      LOGO: fedora-logo-icon
      DEFAULT_HOSTNAME: chiyuki
      HOME_URL: https://github.com/CavaleriOmar/Chiyuki
      SUPPORT_URL: https://github.com/CavaleriOmar/Chiyuki/issues
      BUG_REPORT_URL: https://github.com/CavaleriOmar/Chiyuki/issues

# ===================================================================================
# --- FILES
# ===================================================================================
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

# ===================================================================================
# --- PRE-INSTALLAZIONE
# ===================================================================================
  - type: dnf
    install:
      packages:
#-?        - dnf5-plugin-copr
        - dnf-plugins-core

# ===================================================================================
# --- REPO TERRA
# ===================================================================================
  - type: script
    snippets:
      - |
        sudo dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release terra-gpg-keys

# ===================================================================================
# --- REPO RAKUOS
# ===================================================================================
  - type: dnf
    repos:
      files:
        - https://repo.rakuos.org/rakuos.repo
#      nonfree: negativo17 --- NON USARE

# ===================================================================================
# --- COPR da abilitare
# ===================================================================================
  - type: dnf
    repos:
      copr:
        - ama1470/kwin-effects-glass
        - atim/starship
        - bieszczaders/kernel-cachyos
        - bieszczaders/kernel-cachyos-addons
        - catpieleaf/kernel-p03
        - deltacopy/darkly
        - errornointernet/klassy
        - infinality/kwin-effects-better-blur-dx
        - joviatrix/winboat
        - linuxgamerlife/lgl-scxctl-manager
        - predze/ludora
        - scujas/plasma-applet-appgrid
        - ublue-os/akmods
        - ublue-os/bazzite
        - ublue-os/staging
        - ublue-os/packages

# ===================================================================================
# --- RIMOZIONE PACCHETTI
# ===================================================================================
  - type: dnf
    remove:
      packages:
        - fcitx5
        - firefox
        - flatpak-kcm
        - input-remapper-gtk
        - plasma-settings
        - sunshine
        - tuned
        - tuned-ppd
        - zram-generator-defaults

# ===================================================================================
# --- KERNEL & SCHEDULER
# ===================================================================================
  - type: dnf
    install:
      packages:
        - ananicy-cpp
        - bore-sysctl
        - btrfs-assistant
        - cachyos-ananicy-rules
        - cachyos-ksm-settings
        - cachyos-settings
#        - dmemcg-booster
#        - kernel-p03
        - lgl-scxctl-manager
#        - lm_sensors
        - scx-scheds
        - scx-tools
        - scxctl
        - sysctl
#        - xone-kmod
#        - xone-kmod-common

# ===================================================================================
# --- PACCHETTI BASE FONDAMENTALI
# ===================================================================================
  - type: dnf
    install:
      packages:
        - btop
#        - curl
        - floorp
        - fwupd
        - langpacks-it
        - micro
        - python3-pip
        - rustup
        - ryzenadj
#        - supergfxctl
        - starship
        - terra-release-extras
        - terra-release-mesa
#        - terra-release-multimedia --- DA ASPETTARE
        - tlp
#        - zsh

# ===================================================================================
# --- PACCHETTI UBLUE
# ===================================================================================
  - type: dnf
    install:
      packages:
        - bazzite-portal
        - topgrade
        - ublue-brew
        - ublue-fastfetch
#        - yafti - da installare con pip

# ===================================================================================
# --- PACCHETTI EXTRA
# ===================================================================================
  - type: dnf
    install:
      packages:
        - winboat

# ===================================================================================
# --- PACCHETTI KDE PLASMA
# ===================================================================================
  - type: dnf
    install:
      packages:
        - darkly
#        - fancontrol-gui
        - fancontrol-gui-kcm
        - fancontrol-gui-plasmoid
        - kcalc
#        - kcm_gamecontroller
        - kcm_systemd
#        - kcm_ublue
        - kdenlive
        - klassy
#        - krunner-yafti - dà un problema di dipendenze
#        - kunifiedpush
        - kwin-effects-better-blur-dx
        - kwin-effects-glass
#        - kwrite
        - okular
        - plasma-applet-appgrid
        - plasma-discover
#        - plasma-discover-flatpak
        - plasma-discover-kns
        - plasma-discover-libs
        - plasma-discover-notifier
#        - plasma-discover-offline-updates
#        - plasma-discover-rpm-ostree
#        - supergfxctl-plasmoid

# ===================================================================================
# --- PACCHETTI GAME
# ===================================================================================
  - type: dnf
    install:
      packages:
        - coolercontrol
        - coolercontrold
        - gamescope
        - lact

# ===================================================================================
# --- PULIZIA FLATPAK INDESIDERATI
# ===================================================================================
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        remove: # replace default Firefox with Waterfox
        - org.kde.kcalc
        - org.kde.okular
#        scope: user # Also add Flathub user repo, but no user packages

# ===================================================================================
# --- FLATPAK DI SISTEMA
# ===================================================================================
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
        - com.clustta.clustta
#        - io.github.kolunmi.Bazaar
        - io.github.N3kosempai.klia-store
        - io.github.prateekmedia.appimagepool
        - io.github.getnf.embellish
#        - page.codeberg.jakobdev.jdsystemmonitor
        - xyz.ketok.Speedtest
#        scope: user # Also add Flathub user repo, but no user packages

# ===================================================================================
# --- SCRIPT VARI
# ===================================================================================
#  - type: script
#    scripts:
#      - install-bazzite-kernel.sh
#      - install-cachyos-kernel.sh
#      - install-kernel-p03.sh
#      - oh-my-zsh.sh

# ===================================================================================
# --- FIRMA
# ===================================================================================
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

# --- FINE
