---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# ==================================================================================
# === LA MIA DISTRO ================================================================
# ==================================================================================
# Nata in risposta a Nobara, non a caso ho scelto una mia waifu per il nome
# Potrebbe passare a Balalaika, Roberta, Medusa... o anche Aizen... o persino essere
# il primo passo per il mio sogno, Vesta
name: chiyuki
# description will be included in the image's metadata
description: ISO a uso personale, per test e lavoro.
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
modules:

# ==================================================================================
# === OS RELEASE ===================================================================
# ==================================================================================
  - type: os-release
    properties:
      ID: chiyuki
#      VERSION_ID: 44
      VERSION_CODENAME: Aaroniero # personaggi di Bleach per la 0.x
      NAME: chiyuki
      PRETTY_NAME: Chiyuki (AuroraOS)
#      LOGO: fedora-logo-icon
      DEFAULT_HOSTNAME: chiyuki
      HOME_URL: https://github.com/CavaleriOmar/Chiyuki
      SUPPORT_URL: https://github.com/CavaleriOmar/Chiyuki/issues
      BUG_REPORT_URL: https://github.com/CavaleriOmar/Chiyuki/issues

# ==================================================================================
# === FILES =======================================================================
# ==================================================================================
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it)
#                      into your image's root folder /

# ==================================================================================
# === PRE-INSTALLAZIONE ============================================================
# ==================================================================================
  - type: dnf
    install:
      packages:
#-?        - dnf5-plugin-copr => credo sia superfluo
        - dnf-plugins-core

# ==================================================================================
# === REPO RAKUOS e TERRA ==========================================================
# ==================================================================================
  - type: script
    scripts:
      - addrepo-rakuos.sh
#      - addrepo-terra.sh

# ==================================================================================
# === PACCHETTI - REPO - COPR ======================================================
# ==================================================================================
  - type: dnf
    repos:
#      cleanup: true => disabilita i COPR dopo l'uso, credo
      files:
#        - https://repo.protonvpn.com/fedora-44-stable/protonvpn-stable-release.repo
#        => dà errore 404
        - https://repo.rakuos.org/rakuos.repo
      copr:
        - ama1470/kwin-effects-glass
        - atim/starship
        - bieszczaders/kernel-cachyos
        - bieszczaders/kernel-cachyos-addons
        - catpieleaf/kernel-p03
        - deltacopy/darkly
        - errornointernet/klassy
        - infinality/kwin-effects-better-blur-dx
        - joviatrix/winboat
        - linuxgamerlife/lgl-scxctl-manager
        - predze/ludora
        - scujas/plasma-applet-appgrid
        - ublue-os/akmods
        - ublue-os/bazzite
        - ublue-os/staging
        - ublue-os/packages
# === PULIZIA PACCHETTI INDESIDERATI ===============================================
    remove:
      packages:
        - fcitx5
        - firefox
        - flatpak-kcm
        - input-remapper-gtk
        - plasma-settings
        - sunshine
        - tuned
        - tuned-ppd
        - zram-generator-defaults
# === INSTALLAZIONE PACCHETTI ======================================================
    install:
      skip-unavailable: true
      packages:
# === KERNEL & SCHEDULER ===========================================================
        - ananicy-cpp
        - bore-sysctl
        - btrfs-assistant
        - cachyos-ananicy-rules
        - cachyos-ksm-settings
        - cachyos-settings
#        - dmemcg-booster => non so
#        - kernel-p03 => aspettiamo
        - lgl-scxctl-manager
#        - lm_sensors
#        => già presente
        - scx-scheds
        - scx-tools
        - scxctl
        - sysctl
#        - xone-kmod
#        - xone-kmod-common
# === PACCHETTI BASE FONDAMENTALI ==================================================
        - btop
#        - curl
#        => già presente
        - floorp
        - fwupd
        - langpacks-it
        - micro
        - python3-pip
        - rustup
        - ryzenadj
#        - supergfxctl => non mi serve con una sola GPU
        - starship
        - terra-release-extras
        - terra-release-mesa
#        - terra-release-multimedia => DA ASPETTARE
        - tlp
#        - zsh => già presente
# === PACCHETTI UBLUE ==============================================================
        - bazzite-portal
        - topgrade
        - ublue-brew
        - ublue-fastfetch
#        - yafti - da installare con pip
# === PACCHETTI KDE PLASMA =========================================================
        - darkly
#        - fancontrol-gui
        - fancontrol-gui-kcm
        - fancontrol-gui-plasmoid
        - kcalc
#        - kcm_gamecontroller
        - kcm_systemd
#        - kcm_ublue
        - kdenlive
        - klassy
#        - krunner-yafti => dà un problema di dipendenze
#        - kunifiedpush => già presente
        - kwin-effects-better-blur-dx
        - kwin-effects-glass
#        - kwrite => già presente
        - okular
        - plasma-applet-appgrid
        - plasma-discover
        - plasma-discover-flatpak
        - plasma-discover-kns
        - plasma-discover-libs
        - plasma-discover-notifier
#        - plasma-discover-offline-updates
        - plasma-discover-rpm-ostree
#        - supergfxctl-plasmoid => ho una sola GPU
# === PACCHETTI EXTRA ==============================================================
        - coolercontrol
        - coolercontrold
        - gamescope
        - lact
#        - proton-vpn-gtk-app => per l'errore di cui sopra
        - winboat
# === PACCHETTI LOCALI =============================================================
#        - ./plasma-wallpaper-effects-2.1.0-2.1.noarch.rpm
#        - ./proton-pass-1.39.1-1.x86_64.rpm

# ==================================================================================
# === FLATPAK=======================================================================
# ==================================================================================
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
# === PULIZIA FLATPAK INDESIDERATI =================================================
        remove: # replace default Firefox with Waterfox
        - org.kde.kcalc
        - org.kde.okular
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
        - com.clustta.clustta
#        - io.github.kolunmi.Bazaar
        - io.github.N3kosempai.klia-store
        - io.github.prateekmedia.appimagepool
        - io.github.getnf.embellish
#        - page.codeberg.jakobdev.jdsystemmonitor
        - xyz.ketok.Speedtest
#        scope: user # Also add Flathub user repo, but no user packages

# ==================================================================================
# === SCRIPT VARI ==================================================================
# ==================================================================================
  - type: script
    scripts:
#      - install-bazzite-kernel.sh
#      - install-cachyos-kernel.sh
      - install-cybergrub-2077.sh
#      - install-kernel-p03.sh
#      - oh-my-zsh.sh

# ==================================================================================
# === FIRMA ========================================================================
# ==================================================================================
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

# === FINE =========================================================================
