name: bluebuild
on:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
        # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here
          - recipe.yml
    steps:
      # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: -----BEGIN ENCRYPTED SIGSTORE PRIVATE KEY-----
eyJrZGYiOnsibmFtZSI6InNjcnlwdCIsInBhcmFtcyI6eyJOIjo2NTUzNiwiciI6
OCwicCI6MX0sInNhbHQiOiJQaWdQNGhZLzN3bTdzSk82NDVqZG5ZRlJDdXAzWmFv
RW9mWDRUUzIzd3RzPSJ9LCJjaXBoZXIiOnsibmFtZSI6Im5hY2wvc2VjcmV0Ym94
Iiwibm9uY2UiOiIxVkExeEw1MDRxN2huV0o0T2xaa0ptNUtUcjdza2p4USJ9LCJj
aXBoZXJ0ZXh0Ijoic1lrbVp6ZmxMeGtVc1ltVjY1L1lWNFpEdUhOZGYwUWJsMGNu
d0RCRTFUVGdRR0RpVmtCdGx4Rk9RWnRCNEVCY0hqcjRjRGVQQlZ6LytacWFUWG42
MWFEV2FaRkorM2RVSXZ0TUNIVVJ6MkxSaTI4YkFHVTYvQ3RKT0pPVTJPeGNPVkJG
cGRUemRHNEpPZVEvTW5rY3RFOTFrYlplL2lETStwZWVUWjNnaitBQ2xFb3U2YjE4
L2JYVDhMTUdWak9aRVl3SXAvWmYxSXRIRFE9PSJ9
-----END ENCRYPTED SIGSTORE PRIVATE KEY-----
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: true
